### ISSUE TITLE
Implement Matchers and Scorers

### ISSUE THREAD

**Issue by DerekCresswell** [CSC207-UofT/course-project-gries-fan-club#26]
We should have matchers try and return scores instead of recipes, ie associate each recipe with a match score. There will be a few moving parts to this.

- [x] Matchers will have to have a strong interface to use. Ensure proper functionality is present.
- [x] Matchers should return a score, IE float, associated with a recipe. How should this be represented, score class?, key value pairs for names and scores?
    - This score should likely take the form of x in [0,1] for relevance. This allows us to do a few things:
        - We can easily implement boolean matchers by only returning 0 or 1
        - Save space and power by not returning any 0 scores, ie only return things that are somewhat relevant.
        - Allow for mixed scores, ie matching one tag is boolean, but matching 2 or 3 gives it a 2/3 score.
- [x] Can implement other types of matchers.
- [ ] Implement a scorer, which works on a list of matchers and to find the best matching recipe by averaging the score from each of the matchers that scored a recipe (IE one matcher, 100% of the score, 2 and it's 50%)
    - Some discussion could be had. I think this may be interesting but also perhaps too much. Let me know if this does not seem useful. Otherwise we can just return recipes.

Further notes, some communication is to be had as we may want this to work with entity ID's instead (see #25 ). As well, I'd lik to try and leave the storages responsible for searching for entities and have the matchers just feed criteria to the storages. This might need more implementation of the storages (see #22 ).

**Comment by gerd-bizi** [comment]
Redoing the Matchers. The Matchers only seem to be used for tags. Therefore, the interface will be called TagMatcher, and will create classes that implement it based on the entity. (recipe, ingredient)

**Comment by DerekCresswell** [comment]
> Redoing the Matchers. The Matchers only seem to be used for tags. Therefore, the interface will be called TagMatcher, and will create classes that implement it based on the entity. (recipe, ingredient)

I don't think I we should do this. If we have a scorer class which averages many different matchers, it should work on an interface that is not tag specific.

There should be a `Matcher` interface with some methods to get its matching scores for us. I think the matchers should be given criteria at construction and then run (then cache) the search results. This can be taken by the scorer to average out.
Then we will have many specific matchers, `TagMatcher` will know how to rank recipes via tags, `NameMatcher` will know how to rank them based on names or regex, `IngredientMatcher` might know how to score recipes via a list of required ingredients, and on.

This is why we want a matcher interface in the first place.

**Comment by gerd-bizi** [comment]
That makes sense. Would you like to then instead have sub-interfaces of TagMatcher for ingredients and recipes.

I also need some extra clarification. Tags are used for specialty foods. (ie. gluten-free, lactose-free) For a recipe to be considered for a tag, it needs to have all of its recipeitems have that certain tag. Would our storages for the recipes need to initialize tags for them?

**Comment by gerd-bizi** [comment]
After convo with Ariel, redoing the Matchers are TagMatcher and IngredientMatcher. The TagMatcher will return whether or not a tag is fulfilled in a recipe. The IngredientMatcher will have a method that returns the % of ingredients of a recipe that a list of ingredients has. The Scorer will act more as a _controller_ for the Matchers where it will filter through the results of the QuantityMatcher VS the TagMatcher.
There aren't enough matchers (right now) to warrant an averager.

**Comment by gerd-bizi** [comment]
implemented nameMatchers, need help w the regex.
Scorers implemented with 70/15/15 balance for name/ing/tag.

**Comment by DerekCresswell** [comment]
This is still following the idea that matchers pair recipes with a 0 to 1 score based on its "match percentage" and the scorer averages many matchers though? There is no separate average-er just to be clear.

Is it easier to have the tag matcher only match a single tag and instead match lists of tags by creating multiple tag matchers?
