### ISSUE TITLE
Create base list of Tags, Ingredients, Recipes, and RecipeItems

### ISSUE THREAD

**Issue by DerekCresswell** [CSC207-UofT/course-project-gries-fan-club#41]
Though we are able to extend our program to access data from anywhere, we will not be doing that yet as it massively increases the demands for our data sanitization code (loaders). But we can do it later.

For now, we should have some base lists to work with. For each of the entities we will compile a large enough dataset to properly showcase our program. We will do this initially in JSON. Formats will be posted after #34

**Comment by DerekCresswell** [comment]
Aim to create around 15, 20 recipes. They can be simple, its more about showing functionality. To not mess with ids, you should actually create the entities in code and serialize them with my serialisers (will be posted very soon, even before they are out you can just write the object constructors). Do this and you don't even need to worry about the data structure.

IE:
```
Tag tag1 = new Tag("dairy");
....

TagSerializer serial = new TagSerializer();
for each tag:
  addToList(serial.serializeEntity(tag))

JSONFileIO jsonIO = new JSONFileIO();

FileWriter writer = new FileWriter("output.txt");
jsonIO.save(rows, writer);
writer.close();
```

And thats the general idea. Write all of your entities into the program at once, but serialize them separately. This is because we must reference the correct id's so a recipe must refer to the tag within the same instance of the program.

Also, obviously pseudo code, just look up opening files in java or whatever you need. Text me for clarifcation.

**Comment by DerekCresswell** [comment]
Of use to you may be the standard functions; `List.of()` and `Map.of()`

**Comment by gerd-bizi** [comment]
Recipes being created.
