### ISSUE TITLE
Create Use Cases 

### ISSUE THREAD

**Issue by arieldeveloper** [CSC207-UofT/course-project-gries-fan-club#49]
Will be making use case classes

That means, it takes in storage, matchers, commands and then executes them to get a result. 

The goal is to be able to use these classes and then plug in a command line or a UI. This is the middle layer between the backend and the front end. 

- [ ] Create a mock command class and interface so that you can use it
- [ ]  Create a way to take in a matcher, storage and command and execute as the input suggested

**Comment by ezrarp** [comment]
- [ ] creates ingredients
- [ ] create recipes 
- [ ] create Ingredient Storage
- [ ] create fridge
- [ ] create Recipe Items for the recipe 
- [ ] create the matcher and execute it.
