### ISSUE TITLE
Create Phase 2 Design Document

### ISSUE THREAD

**Issue by DerekCresswell** [CSC207-UofT/course-project-gries-fan-club#75]
We need to revise and create a second edition of our Design Document from phase 1.

This part of the project is EXTREMELY important marks wise. We must spend time on this; it cannot be left until the end.
The requirements can be found on Quercus. The most important thing is that we must be MUCH more technical than Phase 1 was.

Place in the file `phase2/design_document.md`.

**Comment by ezrarp** [comment]
-[] Update class diagram
