### ISSUE TITLE
Augment and improve command / response classes

### ISSUE THREAD

**Issue by DerekCresswell** [CSC207-UofT/course-project-gries-fan-club#76]
Commands, use cases, and responses all belong together in one package. Update the response interface to include diagnostic information (error and messages) and other returning information.

Describe the command class with it's proper purposes.

**Comment by arieldeveloper** [comment]
What needs to be done: 

- [ ] move commands, use cases and responses into one package 
- [ ] make responses one class and make sure it just has a bunch of constructors that it can take in
- [ ] Allow for error and messages to be included in the diagnostic information 
- [ ] add comments on how the command class is used for documentation purposes in all of the use cases

**Comment by DerekCresswell** [comment]
> * [ ]  make responses one class and make sure it just has a bunch of constructors that it can take in
We need an interface that outlines what responses must be, whatever seems reasonable should be here. But not constructors in an interface. Decide what functions should responses have and how should it be set / retrieved. Remember, constructors are for services.

> * [ ]  Allow for error and messages to be included in the diagnostic information
Only what is needed and implement it however it is needed. Should it have exceptions, just info, error codes, what works best.

> * [ ]  add comments on how the command class is used for documentation purposes in all of the use cases
Make sure this is speaking at  a high level. The code describes itself, you need to describe its interaction and place within the whole system.

**Comment by arieldeveloper** [comment]
@DerekCresswell 

The response class should just take in any data. Does that mean we should make it take a list that contains a generic that can be anything? 

For example something like this: 
```
class ResponseImpl implements Response  
     List<T> data; 
     public ResponseImpl (List<T> data) { 
          this.data = data;
      }
}

 ```

Because we do need to take in a list of recipes and a list of ingredients (possibly something else as well) so we can pass it back to the controller and then GUI.

**Comment by DerekCresswell** [comment]
I'm not sure if generic data is the best. Because on the front-end we must then assume that the generic objects are actually some type we understand. This makes errors easy to come by.

I'm not sure what the best idea is, but this means we can ask ourselves what info does a front-end (not "the android frontend") needs. Can every response we'd ever make (ie responses from the commands on the specification) be answered with a "success" indicator and a (possibly empty) list of recipes?

One idea that might help guide this decision is that all of the information displayed in a front-end is inherently a detail. Since we build the front-end with the back-end in mind, we can assume that the front-end can display whatever text is appropriate, as in the back end doesn't need to return a string "we  found these recipes for you", thats something the front-end can just do for itself when appropriate
