### ISSUE TITLE
Cleaning up CLEAN Architecture Violations.

### ISSUE THREAD

**Issue by gerd-bizi** [CSC207-UofT/course-project-gries-fan-club#85]
Please comment issues that you see and fix them.

- [x] SRP violated by RecipeStorageImpl, uses a Matcher-type method
- [x] SRP violated by IngredientMatcher, uses a scoring method, return10RecipesMatched
- [x] OC violated by IngredientMatcher, return10RecipesMatched is not open for extension, provide a variable instead to specify amount of ingredients returned

**Comment by arieldeveloper** [comment]
Yes, these all make sense, need to be changed.
