### ISSUE TITLE
RecipeItem decorator

### ISSUE THREAD

**Issue by ezrarp** [CSC207-UofT/course-project-gries-fan-club#92]
Simpify the ingredient class to a decorator.

**Comment by arieldeveloper** [comment]
WHAT TO DO:
- [ ] remove the old classes 
- [ ] make only one recipe item impl
- [ ] one display method that takes in the parameters like quantity, name etc. 
- [ ] update the tests

**Comment by DerekCresswell** [comment]
Closed in #101
